database:
  user: your_username
  pass: your_password
  dbname: your_database_name
  host: localhost
  port: 5432

production: false

http_server:
  port: 3000

jwt_signing_key: your_key
